### ISSUE TITLE
I tried using this and python just says it can't find the file/directory

### ISSUE THREAD

**Issue by osu4GBRAM** [TheScienceElf/Video-to-Text#1]
I try entering "python3 imageToTextColor.py icon.png", and it returns python3: can't open file 'D:\\Video-to-Text-main\\imageToTextColor.py': [Errno 2] No such file or directory. I tried with the example and it still didn't work. Please help.

**Comment by TheScienceElf** [comment]
Looks like it was a typo in the README. The script is actually named `imgToTextColor.py`.
