### ISSUE TITLE
Error while compiling: /bin/sh not found

### ISSUE THREAD

**Issue by JKakaofanatiker** [TheScienceElf/Video-to-Text#3]
I tried to compile a playback executable for Linux on Linux and got the following error:
```
xxd -i data > data.h
/bin/sh: Zeile 1: xxd: Kommando nicht gefunden.
make: *** [Makefile:7: data.h] Fehler 127
```
It can't find /bin/sh for some reason.

Translation:
Zeile = Line
Kommando nicht gefunden = Command not found
Fehler = Error

**Comment by chfour** [comment]
Install `xxd`, it should pull Vim with it.

**Comment by JKakaofanatiker** [comment]
Thanks
