### ISSUE TITLE
No module named ´numpy´

### ISSUE THREAD

**Issue by Juliasmatius** [TheScienceElf/Video-to-Text#6]
Traceback (most recent call last):
  File "I:\vidtext\videoToTextColor.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by Rafikasya05** [comment]
you dont have numpy

try 
"pip install numpy"
on command line

**Comment by risangbaskoro** [comment]
or better, try `python -m pip install numpy` to install numpy in your current python environment

**Comment by CDSkyward** [comment]
I am having the same issue even after doing the command python -m pip install numpy 
![image](https://user-images.githubusercontent.com/92672257/166825120-b08567f9-e331-4bd5-8013-79815a22f20f.png)

**Comment by risangbaskoro** [comment]
@RealPogger

You can run `python3 -m pip install numpy`.

The reason it's not working is you are installing the numpy package in your python 2 environment, which I assume is still version 2.x, but you execute `python3` (Python 3.x) to run the `videoToTextColor.py`.

You can also try `pip3 install numpy` to install numpy in `python3`.

**Comment by Juliasmatius** [comment]
i got an email about these replyes and i was like why i
does someone/something with the name RealPoggers have my email before i relized it was from gitgub

**Comment by Juliasmatius** [comment]
github is hard to type and walk

**Comment by Juliasmatius** [comment]
oh yea and where do i run it? the commamd
