### ISSUE TITLE
gcc compilation error?

### ISSUE THREAD

**Issue by tjFreerey** [TheScienceElf/Video-to-Text#9]
I haven't used gcc enough to understand what I'm looking at, but I keep getting a message that says `gcc -Wall -I../include -I ./include -L../lib -os -o playback playback.c` any time I try to make the playback file in Linux via `make playback`. The file I get is completely useless and this error makes no sense to me whatsoever.

**Comment by CatKasha** [comment]
Did you get any other errors? Like NumPy or OpenCV module is not installed for Python?
On Ubuntu `make playback` works fine for me and that gcc line is not error, its just output from make that shows what command is running right now
Try manually build playback:
```
python3 convert.py
xxd -i data > data.h
gcc -Wall -o playback playback.c
```

**Comment by tjFreerey** [comment]
> Did you get any other errors? Like NumPy or OpenCV module is not installed for Python? On Ubuntu `make playback` works fine for me and that gcc line is not error, its just output from make that shows what command is running right now Try manually build playback:
> 
> ```
> python3 convert.py
> xxd -i data > data.h
> gcc -Wall -o playback playback.c
> ```

I didn't get any other errors during the process. When I manually build the playback like you did here, it works fine -- albeit there's no color and trying to change the resolution results in the video not rendering correctly. At least, unlike `videoToTextColor.py`, this runs at the correct framerate.

**Comment by CatKasha** [comment]
As far i understand playback dint support colors
To fix render check this comment https://github.com/TheScienceElf/Video-to-Text/issues/8#issuecomment-1075029504
